// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKEq7TaiuagZ8lTPiXfy5VyBjM-1Ykt4k',
    appId: '1:388988662520:web:06d0aaeea3616a2e19c10d',
    messagingSenderId: '388988662520',
    projectId: 'mesclainvest-fe733',
    authDomain: 'mesclainvest-fe733.firebaseapp.com',
    storageBucket: 'mesclainvest-fe733.firebasestorage.app',
    measurementId: 'G-WKYWBFKXX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nZQpwuLP8uMx5a-1yuJgSVtSLh7Ay0g',
    appId: '1:388988662520:android:3ebe3eb55363c33019c10d',
    messagingSenderId: '388988662520',
    projectId: 'mesclainvest-fe733',
    storageBucket: 'mesclainvest-fe733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAyFL4UMx0oHQtgLQbMlEZwcWjsYBj0zA',
    appId: '1:388988662520:ios:246b69fe7cc1b45519c10d',
    messagingSenderId: '388988662520',
    projectId: 'mesclainvest-fe733',
    storageBucket: 'mesclainvest-fe733.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAyFL4UMx0oHQtgLQbMlEZwcWjsYBj0zA',
    appId: '1:388988662520:ios:246b69fe7cc1b45519c10d',
    messagingSenderId: '388988662520',
    projectId: 'mesclainvest-fe733',
    storageBucket: 'mesclainvest-fe733.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKEq7TaiuagZ8lTPiXfy5VyBjM-1Ykt4k',
    appId: '1:388988662520:web:d8a8bb7995799bef19c10d',
    messagingSenderId: '388988662520',
    projectId: 'mesclainvest-fe733',
    authDomain: 'mesclainvest-fe733.firebaseapp.com',
    storageBucket: 'mesclainvest-fe733.firebasestorage.app',
    measurementId: 'G-R0C5CD4W6X',
  );
}
